#!/usr/bin/env bash
# Phase 250 — Stack-wide log rotation with 7-day retention.
#
# Why: each *arr/bazarr/tautulli/unpackerr/tdarr instance independently
# rotates its own logs but keeps 50+ generations (default config). Across
# the stack that's 200-500 MB of log mass + accumulates indefinitely.
# When the operator's quota gets tight (see 2026-05-21 incident), log
# mass becomes the difference between healthy and SQLite-I/O-error wall.
#
# Strategy:
#   1. Write a comprehensive ~/.config/logrotate.conf that covers every
#      log-producing app's known location, with maxage 7 (deletes
#      generations >7 days) + rotate 7 + daily.
#   2. Use copytruncate so apps don't need to be restarted to release
#      their open log file handles (Sonarr/Radarr otherwise keep writing
#      to the rotated file).
#   3. One-shot: force-delete anything older than 7 days NOW, so we don't
#      wait up to a week for logrotate's first pass.
#   4. The pre-existing user logrotate.timer (weekly) keeps running it.
#
# Idempotent. Run any time. Re-running is safe — config is overwritten,
# old-file purge is a no-op when there's nothing >7 days.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/../.." && pwd)"
source "$HERE/../lib/ssh.sh"
source "$HERE/../lib/log.sh"

log_info "Phase 250: stack-wide logrotate install (7-day retention)"

sshm 'bash -s' <<'REMOTE'
set -euo pipefail

# ----------------------------------------------------------------------
# Step 1 — write the canonical logrotate config.
#
# logrotate options used:
#   daily         — rotate at most once per day
#   rotate 7      — keep 7 generations max
#   maxage 7      — delete generations older than 7 days even if rotate>7
#   compress      — gzip rotated copies (saves ~80%)
#   delaycompress — don't compress the most-recent rotation yet (some
#                   apps mmap their logs; delaying keeps them readable)
#   missingok     — don't error if a glob matches nothing
#   notifempty    — don't rotate a zero-byte log
#   copytruncate  — copy then truncate the live file (no app restart
#                   needed — *arr stack would keep writing to the
#                   rotated path otherwise)
#   sharedscripts — postrotate runs once even if multiple files matched
# ----------------------------------------------------------------------
cat > ~/.config/logrotate.conf <<'CONF'
# QFlix stack-wide logrotate config — 7-day retention.
# Generated by scripts/configure/250-logrotate-install.sh.
# Run by ~/.config/systemd/user/logrotate.{service,timer} (weekly).

# Global defaults — individual blocks may override.
daily
rotate 7
maxage 7
compress
delaycompress
missingok
notifempty
copytruncate
nomail

# --- *arr stack (Sonarr / Radarr / Sonarr2 / Radarr2 / Prowlarr) ---
# These rotate internally to <name>.<N>.txt and <name>.debug.<N>.txt but
# keep up to 50 generations each. Cap at 7 days.
"/home/quadstronaut/.apps/sonarr/logs/*.txt" {
  size 50M
}
"/home/quadstronaut/.apps/sonarr2/logs/*.txt" {
  size 50M
}
"/home/quadstronaut/.apps/radarr/logs/*.txt" {
  size 50M
}
"/home/quadstronaut/.apps/radarr2/logs/*.txt" {
  size 50M
}
"/home/quadstronaut/.apps/prowlarr/logs/*.txt" {
  size 50M
}

# --- Bazarr / Bazarr2 (different dir name: 'log' singular) ---
"/home/quadstronaut/.apps/bazarr/log/*.log" {
  size 50M
}
"/home/quadstronaut/.apps/bazarr2/log/*.log" {
  size 50M
}

# --- Tautulli ---
"/home/quadstronaut/.apps/tautulli/logs/*.log" {
  size 50M
}
"/home/quadstronaut/.apps/tautulli/logs/*.log.*" {
  size 50M
}

# --- Unpackerr — logs to app root, not a logs/ subdir ---
"/home/quadstronaut/.apps/unpackerr/*.log" {
  size 50M
}

# --- Tdarr server + node ---
"/home/quadstronaut/.apps/tdarr/logs/*.log" {
  size 50M
}

# --- Kometa / Recyclarr / Buildarr / Upgradinatorr / Maintainerr ---
"/home/quadstronaut/.apps/kometa/config/logs/*.log" {
  size 50M
}
"/home/quadstronaut/.apps/recyclarr/logs/*.log" {
  size 50M
}
"/home/quadstronaut/.apps/buildarr/logs/*.log" {
  size 50M
}
"/home/quadstronaut/.apps/maintainerr/logs/*.log" {
  size 50M
  missingok
}

# --- qBittorrent ---
"/home/quadstronaut/.apps/qbittorrent/logs/*.log" {
  size 50M
  missingok
}

# --- Stream-stats / qflix-newsletter / homarr / listmonk ---
"/home/quadstronaut/.apps/stream-stats/logs/*.log" {
  size 50M
  missingok
}
"/home/quadstronaut/.apps/qflix-newsletter/logs/*.log" {
  size 50M
  missingok
}
"/home/quadstronaut/.apps/listmonk/logs/*.log" {
  size 50M
  missingok
}

# --- Plex (under PlexMediaServer's own dir; large server log) ---
"/home/quadstronaut/.apps/plex/Library/Application Support/Plex Media Server/Logs/*.log" {
  size 50M
  missingok
}
CONF

echo "wrote ~/.config/logrotate.conf"

# ----------------------------------------------------------------------
# Step 2 — purge anything already >7 days. logrotate's maxage will catch
# future rotations, but it doesn't go back and delete pre-existing files
# that match its size/maxage rules. Do that explicitly NOW (one-shot).
# Includes the rotated app-side generations (radarr.26.txt = 122 days
# old as of 2026-05-21).
# ----------------------------------------------------------------------
echo
echo "=== purging pre-existing logs >7 days ==="
PURGED=0
PURGED_BYTES=0
for pattern in \
    "/home/quadstronaut/.apps/sonarr/logs/*.txt" \
    "/home/quadstronaut/.apps/sonarr2/logs/*.txt" \
    "/home/quadstronaut/.apps/radarr/logs/*.txt" \
    "/home/quadstronaut/.apps/radarr2/logs/*.txt" \
    "/home/quadstronaut/.apps/prowlarr/logs/*.txt" \
    "/home/quadstronaut/.apps/bazarr/log/*.log*" \
    "/home/quadstronaut/.apps/bazarr2/log/*.log*" \
    "/home/quadstronaut/.apps/tautulli/logs/*.log*" \
    "/home/quadstronaut/.apps/unpackerr/*.log" \
    "/home/quadstronaut/.apps/tdarr/logs/*.log" \
    "/home/quadstronaut/.apps/kometa/config/logs/*.log" \
    "/home/quadstronaut/.apps/recyclarr/logs/*.log" \
    "/home/quadstronaut/.apps/buildarr/logs/*.log" \
    "/home/quadstronaut/.apps/maintainerr/logs/*.log" \
    "/home/quadstronaut/.apps/qbittorrent/logs/*.log" \
    "/home/quadstronaut/.apps/stream-stats/logs/*.log" \
    "/home/quadstronaut/.apps/qflix-newsletter/logs/*.log" \
    ; do
  # Skip the current "live" log of each app — only delete rotated/older copies
  # that meet the age threshold. logrotate's `notifempty` + `copytruncate` mean
  # the live file is always young (it gets truncated daily).
  for f in $(ls -1 $pattern 2>/dev/null); do
    if [ -f "$f" ]; then
      AGE_DAYS=$(( ( $(date +%s) - $(stat -c %Y "$f") ) / 86400 ))
      if [ "$AGE_DAYS" -gt 7 ]; then
        SZ=$(stat -c %s "$f")
        rm -f "$f"
        PURGED=$((PURGED+1))
        PURGED_BYTES=$((PURGED_BYTES+SZ))
      fi
    fi
  done
done
echo "purged $PURGED file(s), $((PURGED_BYTES/1048576)) MB"

# ----------------------------------------------------------------------
# Step 3 — force-rotate now (don't wait for the weekly timer's next fire).
# This also exercises the config: any syntax error surfaces here.
# ----------------------------------------------------------------------
echo
echo "=== logrotate -f (force-run) ==="
/usr/sbin/logrotate -s ~/.logrotate.status ~/.config/logrotate.conf -f 2>&1 | tail -20 || true
echo
echo "=== logrotate -d (debug-validate, no action) ==="
/usr/sbin/logrotate -s ~/.logrotate.status -d ~/.config/logrotate.conf 2>&1 | grep -E "^(error|considering rotation|rotating log|skipping)" | head -10 || true

# ----------------------------------------------------------------------
# Step 4 — cap systemd user journal at 200M.
# /etc/systemd/journald.conf is root-only; for user journal we get the
# system default. Best we can do without sudo: vacuum any existing
# user journal data >7 days.
# ----------------------------------------------------------------------
echo
echo "=== journalctl --user vacuum (older than 7 days) ==="
journalctl --user --vacuum-time=7d 2>&1 | tail -3 || true
echo "user journal size: $(journalctl --user --disk-usage 2>&1 | head -1)"

# ----------------------------------------------------------------------
# Step 5 — verify timer is enabled (should already be from base image).
# ----------------------------------------------------------------------
echo
echo "=== logrotate.timer status ==="
if systemctl --user is-enabled logrotate.timer >/dev/null 2>&1; then
  echo "logrotate.timer: enabled"
  systemctl --user list-timers logrotate.timer --no-pager 2>/dev/null | grep logrotate || true
else
  echo "WARNING: logrotate.timer not enabled — enabling now"
  systemctl --user enable --now logrotate.timer
fi

REMOTE

log_info "Phase 250 complete — logrotate 7-day retention installed"
