#!/usr/bin/env bash
# Phase 32 — Kometa install. Idempotent.
#  - pyenv (or Astral PBS) Python; venv at ~/.apps/kometa/venv/
#  - clones Kometa-Team/Kometa @ pinned tag (secrets/kometa.version)
#  - generates ~/.apps/kometa/config/config.yml from the operator's tokens
#  - empty metadata stubs in config/metadata/ for operator-curated content
#  - systemd --user TIMER (daily 03:30 + 15min jitter, Nice=15, IO idle)
#  - first-run smoke (--run) before scheduling
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$HERE/../lib/ssh.sh"
source "$HERE/../lib/log.sh"
source "$HERE/../lib/secrets.sh"

# ── Step 1: pre-reqs ────────────────────────────────────────────────────────
[ -f secrets/tmdb.api_key ] || die "missing secrets/tmdb.api_key"
[ -f secrets/plex.token ] || die "missing secrets/plex.token"

# ── Step 2: pin Kometa version (latest stable at first run) ────────────────
if ! secret_exists kometa.version; then
  TAG=$(curl -fsSL https://api.github.com/repos/Kometa-Team/Kometa/releases/latest | grep -oP '"tag_name":\s*"\K[^"]+')
  [ -n "$TAG" ] || die "could not resolve Kometa latest tag"
  secret_write kometa.version "$TAG"
  log_info "pinned kometa.version = $TAG"
fi
KVER=$(secret_read kometa.version)
log_info "kometa version = $KVER"

# ── Step 3: clone + venv (use Astral PBS Python 3.11 from Phase 22) ────────
sshm "KVER='${KVER}' bash -s" <<'CLONESCRIPT'
set -euo pipefail
PY311=$HOME/.local/python311/bin/python3.11
[ -x "$PY311" ] || { echo "FATAL: Astral python3.11 not found at $PY311 — install python-build-standalone 3.11 to ~/.local/python311 (formerly staged by the now-decommissioned Conjurr installer)"; exit 1; }

mkdir -p ~/.apps/kometa/{config,logs,cache}
cd ~/.apps/kometa

# Clone-or-update Kometa pinned to KVER
if [ ! -d kometa/.git ]; then
  git clone --branch "$KVER" --depth 1 https://github.com/Kometa-Team/Kometa.git kometa
else
  cd kometa
  CURRENT=$(git describe --tags --exact-match 2>/dev/null || echo "")
  if [ "$CURRENT" != "$KVER" ]; then
    git fetch --tags --depth 1 origin "$KVER:refs/tags/$KVER" 2>/dev/null || true
    git checkout --quiet "$KVER"
  fi
  cd ..
fi

# Venv (Python 3.11)
if [ ! -d venv ] || ! ./venv/bin/python --version 2>&1 | grep -q "Python 3.11"; then
  rm -rf venv
  $PY311 -m venv venv
fi
./venv/bin/pip install --quiet --upgrade pip wheel
./venv/bin/pip install --quiet --no-cache-dir -r kometa/requirements.txt
./venv/bin/python -c "import requests, ruamel.yaml, plexapi; print('deps ok')"

mkdir -p ~/.apps/kometa/config/metadata ~/.apps/kometa/config/assets
# Kometa flags any empty metadata file as "YAML Error: File is empty" once per
# library reference (4 libs × 2 reads = 8 errors per run). Write a minimal
# valid stub so an unedited install boots clean.
for stub in ~/.apps/kometa/config/metadata/movies.yml ~/.apps/kometa/config/metadata/shows.yml; do
  if [ ! -s "$stub" ]; then
    printf 'metadata: {}\n' > "$stub"
  fi
done
CLONESCRIPT

# ── Step 4: render config.yml ──────────────────────────────────────────────
PLEX_TOKEN=$(secret_read plex.token)
PLEX_HOST=$(secret_read plex.host)
PLEX_PORT=$(secret_read plex.port)
TMDB_KEY=$(secret_read tmdb.api_key)

# Library names match the live Plex install (queried via /library/sections):
#   "QFlix - Movies", "QFlix - Anime Movies", "QFlix - TV", "QFlix - Anime".
# Prior to 2026-05 the libraries were "Pirate Movies"/"Pirate TV Shows"; the
# rename happened upstream and this config was left out of sync, so Kometa
# was failing every run with "Plex Library 'Pirate TV Shows' not found".
# Both movie libraries share movies.yml; both show libraries share shows.yml
# (operator can split if they want library-specific metadata later).
sshm "cat > ~/.apps/kometa/config/config.yml" <<EOF
# Kometa config — Manitoba (generated by scripts/configure/55-kometa-install.sh)
# Operator: extend metadata via config/metadata/{movies,shows}.yml (Phase 33).
# Reference: https://kometa.wiki/en/latest/config/configuration/

libraries:
  QFlix - Movies:
    metadata_path:
      - file: config/metadata/movies.yml
    operations:
      mass_genre_update: tmdb
      mass_studio_update: tmdb
      assets_for_all: true
  QFlix - Anime Movies:
    metadata_path:
      - file: config/metadata/movies.yml
    operations:
      mass_genre_update: tmdb
      mass_studio_update: tmdb
      assets_for_all: true
  QFlix - TV:
    metadata_path:
      - file: config/metadata/shows.yml
    operations:
      mass_genre_update: tmdb
      mass_studio_update: tmdb
      assets_for_all: true
  QFlix - Anime:
    metadata_path:
      - file: config/metadata/shows.yml
    operations:
      mass_genre_update: tmdb
      mass_studio_update: tmdb
      assets_for_all: true

settings:
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  asset_depth: 0
  create_asset_folders: true
  download_url_assets: false
  sync_mode: append
  minimum_items: 1
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: true
  show_unmanaged: true
  save_report: true
  tvdb_language: eng
  overlay_artwork_filetype: webp_lossless

plex:
  url: http://${PLEX_HOST}:${PLEX_PORT}
  token: ${PLEX_TOKEN}
  timeout: 60
  clean_bundles: false
  empty_trash: false
  optimize: false
  verify_ssl: false

tmdb:
  apikey: ${TMDB_KEY}
  language: en
  cache_expiration: 60
EOF
sshm 'chmod 600 ~/.apps/kometa/config/config.yml'
log_info "wrote ~/.apps/kometa/config/config.yml"

# ── Step 5: first-run smoke (--run --no-missing) ───────────────────────────
log_info "first-run smoke (--run --no-missing)... this may take a few minutes"
sshm 'cd ~/.apps/kometa && ./venv/bin/python kometa/kometa.py --config config/config.yml --run --no-missing 2>&1 | tee ~/.apps/kometa/logs/first-run.log | tail -20' || die "Kometa first run failed — see ~/.apps/kometa/logs/first-run.log"
log_info "first-run completed"

# ── Step 6: systemd timer (daily 03:30 + 15min jitter) ─────────────────────
sshm "bash -s" <<'UNITSCRIPT'
set -euo pipefail
cat > ~/.config/systemd/user/kometa.service <<'UNIT'
[Unit]
Description=Kometa metadata + collection run
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
WorkingDirectory=%h/.apps/kometa
ExecStart=%h/.apps/kometa/venv/bin/python %h/.apps/kometa/kometa/kometa.py --config %h/.apps/kometa/config/config.yml --run
Nice=15
IOSchedulingClass=idle
StandardOutput=append:%h/.apps/kometa/logs/kometa.log
StandardError=append:%h/.apps/kometa/logs/kometa.err
UNIT

cat > ~/.config/systemd/user/kometa.timer <<'UNIT'
[Unit]
Description=Kometa daily run (03:30 + 15min jitter)

[Timer]
OnCalendar=*-*-* 03:30:00
RandomizedDelaySec=900
Persistent=true
Unit=kometa.service

[Install]
WantedBy=timers.target
UNIT

systemctl --user daemon-reload
systemctl --user enable --now kometa.timer
systemctl --user list-timers kometa.timer --no-pager | head -3
UNITSCRIPT

sshm 'systemctl --user list-timers kometa.timer --no-pager 2>/dev/null | grep -q kometa.timer' || die "kometa.timer not scheduled"
log_info "Phase 32 complete — Kometa installed; daily timer 03:30 active"
