#!/usr/bin/env python3
"""qflix-audit-live — the LIVE half of the Convergent Audit Regime (L-01..L-07).

Runs ON THE BOX, on its OWN timer, pushing its OWN Kuma monitor. It is
deliberately NOT folded into functional-audit.py or qflix-collect.py: the
operator design law is that every maintenance concern gets its own module, timer
and check so it stays independently swappable and tunable through a server
migration.

WHY THIS CANNOT BE PART OF qflix-audit.py
    Everything here is a property of a running machine, not of a commit:
      L-01 repo unit files vs DEPLOYED unit files (drop-ins like the reaper's
           `--max-pct 100` are DESIGNED to exist only on the box)
      L-02 deployed timers/services with no repo representation at all
      L-03 the live Kuma monitor set (kuma.db; /metrics lies for daily
           self-pushers, which drop out ~22h/day between beats)
      L-04 declared secret keys exist with a sane mode
      L-05 every self-pusher has a PERSISTED push token (the born-mute class)
      L-06 quota / thread-ceiling headroom
      L-07 stale-green push monitors (Kuma restart resets its push-timeout
           timers, so a monitor whose beat was already overdue at restart
           re-greens before it ever pages -- the missed run is invisible)
    These will keep producing new findings forever. That is registered honestly
    in docs/audit-residual-risk.md; it is not a defect of the design.

OUTPUT
    ~/.opt/maint/audit/last-audit.json, carrying a RECORD timestamp
    (`recorded_at`). The repo-side consumer must refuse a stale snapshot by
    RECORD time, never by file mtime — that is C-04 applied to the auditor
    itself, and it is the exact bug cbde5c1 fixed in REA.

EXIT CODES mirror the offline tool: 0 clean / 1 findings / 2 cannot audit.
"""
from __future__ import annotations

import argparse
import datetime as _dt
import json
import os
import re
import subprocess
import sys
from pathlib import Path

EXIT_OK, EXIT_FINDINGS, EXIT_CANNOT_AUDIT = 0, 1, 2

STATE_DIR = Path(os.environ.get("QFLIX_AUDIT_STATE",
                                str(Path.home() / ".opt" / "maint" / "audit")))
# COLON-separated list: QFlix stages units from more than one repo directory.
# A single dir made everything staged elsewhere look like it had no repo origin.
REPO_UNIT_DIRS = [
    Path(x) for x in os.environ.get(
        "QFLIX_AUDIT_REPO_UNITS",
        os.pathsep.join([
            str(Path.home() / "scripts" / "maint" / "systemd"),
            str(Path.home() / "scripts" / "mcp" / "systemd"),
            str(Path.home() / ".opt" / "qflix-src" / "scripts" / "maint" / "systemd"),
            str(Path.home() / ".opt" / "qflix-src" / "scripts" / "mcp" / "systemd"),
        ])
    ).split(os.pathsep) if x
]
REPO_UNITS = REPO_UNIT_DIRS[0]   # retained: single-dir callers/tests

# Units the maintenance system owns outright, in BOTH directions.
OWNED_UNIT_PREFIXES = ("manitoba-maint",)

# The jobs ledger on the box; `may_be_absent: true` opts a unit out of L-01.
JOBS_LEDGER = Path(os.environ.get(
    "QFLIX_AUDIT_JOBS_LEDGER",
    str(Path.home() / ".opt" / "maint" / "jobs.yaml")))


def _may_be_absent() -> set:
    """Unit basenames whose intended terminal state is 'gone'.

    flaresolverr-unsuppress deletes itself once FlareSolverr is healthy, so its
    absence is success, not drift. Declared in the ledger next to the job rather
    than hardcoded here, so the exemption lives where the job does.
    """
    try:
        import yaml                                            # noqa: PLC0415
        data = yaml.safe_load(JOBS_LEDGER.read_text(encoding="utf-8")) or {}
    except Exception:                                          # noqa: BLE001
        return set()
    out = set()
    for _name, v in (data.get("jobs") or {}).items():
        if isinstance(v, dict) and v.get("may_be_absent") and v.get("timer"):
            stem = os.path.basename(str(v["timer"]))
            out.add(stem)
            out.add(stem[:-len(".timer")] + ".service")
    return out


def _is_owned(unit: str, repo_units: set) -> bool:
    """In scope iff plainly ours, or the repo actually ships it.

    Apps whose units are generated by their own installer (kometa, buildarr,
    recyclarr, upgradinatorr, tdarr-node-*, qflix-dash) have no repo unit file by
    design; so do Ultra.cc panel apps (nginx, qbittorrent, listmonk). Neither is
    drift, and flagging them is exactly the false-red noise this regime exists to
    remove.
    """
    return unit.startswith(OWNED_UNIT_PREFIXES) or unit in repo_units
DEPLOYED_UNITS = Path(os.environ.get("QFLIX_AUDIT_DEPLOYED_UNITS",
                                     str(Path.home() / ".config" / "systemd" / "user")))
SECRETS_DIR = Path(os.environ.get("MANITOBA_SECRETS",
                                  str(Path.home() / "secrets")))
KUMA_DB = Path(os.environ.get("QFLIX_KUMA_DB",
                              str(Path.home() / ".apps" / "uptimekuma" / "kuma.db")))
PUSH_TOKENS = SECRETS_DIR / "kuma-push-tokens.json"

MONITOR_NAME = "QFlix Audit Live"
# Token KEY in ~/secrets/kuma-push-tokens.json. Must equal the VALUE this monitor
# is registered under in lib/kuma.py STANDALONE_SELF_PUSH_MONITORS, or the push
# silently no-ops and the monitor goes red for entirely the wrong reason.
KUMA_PUSH_KEY = "qflix-audit-live"


# ---------------------------------------------------------------------------
# pure helpers — unit-tested offline in tests/unit/test_audit_live.py
# ---------------------------------------------------------------------------

def diff_unit_sets(repo: set[str], deployed: set[str]) -> dict[str, list[str]]:
    """L-01/L-02 in their set-theoretic form.

    `deployed_only` is the interesting direction — a unit running on the box that
    no commit describes. `repo_only` is usually benign (units the installer has
    not been asked to enable yet) and is reported at a lower severity.
    """
    return {
        "deployed_only": sorted(deployed - repo),
        "repo_only": sorted(repo - deployed),
        "both": sorted(repo & deployed),
    }


def classify_secret_mode(mode: int) -> str:
    """L-04. World- or group-readable secrets on a SHARED seedbox are the whole
    threat model, so anything past 0600 is called out."""
    if mode & 0o077:
        return "too-permissive"
    return "ok"


def missing_push_tokens(expected: list[str], tokens: dict) -> list[str]:
    """L-05, the born-mute class.

    A canary whose token was never persisted exits 0 in silence and its monitor
    never beats — 32 of 60 monitors were once in some flavour of this state, and
    the reaper's forever-red was a never-persisted token. An empty-string value
    counts as missing: that is precisely how it failed before.
    """
    return sorted(name for name in expected
                  if not str(tokens.get(name) or "").strip())


def parse_quota_pct(df_line: str) -> int | None:
    """L-06. Accepts a `df -P` style line; returns the used percentage."""
    m = re.search(r"(\d+)%", df_line or "")
    return int(m.group(1)) if m else None


def snapshot_is_stale(payload: dict, now: _dt.datetime, max_age_min: int) -> bool:
    """Freshness by RECORD time, never by file mtime.

    A rewritten-in-place file looks fresh to stat(2) while carrying week-old
    content. This is the C-04 class applied to the audit's own artefact.
    """
    raw = (payload or {}).get("recorded_at")
    if not raw:
        return True
    try:
        ts = _dt.datetime.fromisoformat(str(raw).replace("Z", "+00:00"))
    except ValueError:
        return True
    if ts.tzinfo is None:
        ts = ts.replace(tzinfo=_dt.timezone.utc)
    return (now - ts).total_seconds() / 60.0 > max_age_min


# ---------------------------------------------------------------------------
# live collection
# ---------------------------------------------------------------------------

def _unit_names(directory: Path) -> set[str]:
    try:
        return {p.name for p in directory.iterdir()
                if p.suffix in (".service", ".timer")}
    except OSError:
        return set()


def _kuma_monitor_names() -> set[str] | None:
    if not KUMA_DB.exists():
        return None
    try:
        import sqlite3
        con = sqlite3.connect(f"file:{KUMA_DB}?mode=ro", uri=True, timeout=3)
        try:
            rows = con.execute("SELECT name FROM monitor WHERE active=1").fetchall()
        finally:
            con.close()
        return {r[0] for r in rows if r and r[0]}
    except Exception as exc:                                  # noqa: BLE001
        print(f"qflix-audit-live: kuma.db unreadable: {exc}", file=sys.stderr)
        return None


def stale_green_pushers(rows, now: _dt.datetime, slack: float = 1.25) -> list[dict]:
    """L-07, the pure half. `rows` = (name, interval_s, last_beat_utc_str,
    last_status); returns a finding per ACTIVE push monitor whose latest beat
    is GREEN yet older than its own heartbeat window (with slack).

    WHY (2026-08-18 storm audit): Kuma's push-timeout timers live in process
    memory and RESET when Kuma restarts. The host reboot took Kuma down
    04:38-07:36 UTC; the daily self-pushers (reaper, torrent-janitor, audit
    regime) had all just failed against dead services, and on restart their
    25h deadlines were re-armed FROM KUMA BOOT -- pushed past each job's next
    scheduled run, so all three sat GREEN on 36-38h-old beats and the lost
    day could never page. Contrast the REA-liveness canary (70min window):
    its re-armed deadline expired BEFORE the next beat, so it alone paged.

    The slack factor absorbs RandomizedDelaySec and one slow run; 1.25 x 25h
    ~= 31h, well under the 2-day age that means a genuinely lost run.

    Fails open per row: an unparseable beat time yields no finding -- this
    detector exists to catch silence, not to manufacture it from format
    drift. (Kuma writes naive UTC 'YYYY-MM-DD HH:MM:SS.mmm' today.)
    """
    out = []
    for name, interval_s, beat_time, status in rows:
        if status != 1 or not interval_s:
            continue  # red monitors already page; interval 0 has no window
        try:
            t = _dt.datetime.fromisoformat(str(beat_time).split(".")[0])
            t = t.replace(tzinfo=_dt.timezone.utc)
        except ValueError:
            continue
        age = (now - t).total_seconds()
        if age > interval_s * slack:
            out.append({
                "class_id": "L-07", "instance_id": name,
                "detail": "stale-green-%dh-beat-vs-%dh-window"
                          % (age // 3600, interval_s // 3600),
            })
    return out


def _push_monitor_beats():
    """DB half of L-07: (name, interval, latest beat time, latest status) for
    every ACTIVE push-type monitor. None when kuma.db is not readable."""
    if not KUMA_DB.exists():
        return None
    try:
        import sqlite3
        con = sqlite3.connect(f"file:{KUMA_DB}?mode=ro", uri=True, timeout=3)
        try:
            rows = con.execute(
                "SELECT m.name, m.interval, h.time, h.status "
                "FROM monitor m JOIN heartbeat h ON h.id = ("
                "  SELECT id FROM heartbeat WHERE monitor_id = m.id "
                "  ORDER BY time DESC LIMIT 1) "
                "WHERE m.active = 1 AND m.type = 'push'").fetchall()
        finally:
            con.close()
        return rows
    except Exception as exc:                                  # noqa: BLE001
        print(f"qflix-audit-live: kuma.db unreadable for L-07: {exc}",
              file=sys.stderr)
        return None


def collect(expected_monitors: list[str]) -> dict:
    findings: list[dict] = []
    coverage: dict[str, str] = {}

    # L-01 / L-02 ---------------------------------------------------------
    repo_units = set()
    for _d in REPO_UNIT_DIRS:
        repo_units |= _unit_names(_d)
    # Only adjudicate what we own; installer-generated and panel-managed units
    # are out of scope both ways. Exempt units whose terminal state is "gone".
    _exempt = _may_be_absent()
    repo_units = {u for u in repo_units
                  if u.startswith(OWNED_UNIT_PREFIXES) and u not in _exempt}
    deployed_units = {u for u in _unit_names(DEPLOYED_UNITS)
                      if _is_owned(u, repo_units) and u not in _exempt}
    if not repo_units or not deployed_units:
        coverage["L-01"] = coverage["L-02"] = "unavailable"
    else:
        diff = diff_unit_sets(repo_units, deployed_units)
        coverage["L-01"] = coverage["L-02"] = "checked"
        for name in diff["deployed_only"]:
            findings.append({"class_id": "L-02", "instance_id": name,
                             "detail": "deployed-unit-not-in-repo"})
        for name in diff["repo_only"]:
            findings.append({"class_id": "L-01", "instance_id": name,
                             "detail": "repo-unit-not-deployed"})

    # L-03 ---------------------------------------------------------------
    live = _kuma_monitor_names()
    if live is None:
        coverage["L-03"] = "unavailable"
    else:
        coverage["L-03"] = "checked"
        for name in sorted(set(expected_monitors) - live):
            findings.append({"class_id": "L-03", "instance_id": name,
                             "detail": "expected-monitor-absent-from-kuma"})

    # L-04 ---------------------------------------------------------------
    if SECRETS_DIR.is_dir():
        coverage["L-04"] = "checked"
        for p in sorted(SECRETS_DIR.iterdir()):
            if not p.is_file():
                continue
            verdict = classify_secret_mode(p.stat().st_mode & 0o777)
            if verdict != "ok":
                findings.append({"class_id": "L-04", "instance_id": p.name,
                                 "detail": f"secret-mode-{verdict}"})
    else:
        coverage["L-04"] = "unavailable"

    # L-05 ---------------------------------------------------------------
    if PUSH_TOKENS.exists():
        coverage["L-05"] = "checked"
        try:
            tokens = json.loads(PUSH_TOKENS.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            coverage["L-05"] = "unavailable"
            print(f"qflix-audit-live: push tokens unreadable: {exc}", file=sys.stderr)
            tokens = {}
        for name in missing_push_tokens(expected_monitors, tokens):
            findings.append({"class_id": "L-05", "instance_id": name,
                             "detail": "self-pusher-without-persisted-token"})
    else:
        coverage["L-05"] = "unavailable"

    # L-06 ---------------------------------------------------------------
    proc = subprocess.run(["df", "-P", str(Path.home())],
                          capture_output=True, text=True, check=False)
    pct = None
    if proc.returncode == 0:
        lines = proc.stdout.strip().splitlines()
        if len(lines) >= 2:
            pct = parse_quota_pct(lines[1])
    if pct is None:
        coverage["L-06"] = "unavailable"
    else:
        coverage["L-06"] = "checked"
        if pct >= 90:
            findings.append({"class_id": "L-06", "instance_id": "home-quota",
                             "detail": f"quota-{pct}pct"})

    # L-07 ---------------------------------------------------------------
    beats = _push_monitor_beats()
    if beats is None:
        coverage["L-07"] = "unavailable"
    else:
        coverage["L-07"] = "checked"
        findings.extend(
            stale_green_pushers(beats, _dt.datetime.now(_dt.timezone.utc)))

    return {"coverage": coverage, "findings": findings}


def _push_kuma(status: str, msg: str) -> None:
    """Best-effort heartbeat for this auditor's OWN monitor.

    The module docstring said "pushing its OWN Kuma monitor" and main() never
    did. The monitor was registered, given a token, and fed by nobody, so it
    would have gone red on heartbeat timeout -- the born-dead class L-05 exists
    to detect, occurring inside the detector itself.

    A MISSING TOKEN IS REPORTED, never silently skipped: a silent skip is the
    C-09 class this regime enumerates, and the auditor does not get to be an
    instance of it.
    """
    import urllib.parse
    import urllib.request

    token = os.environ.get("QFLIX_AUDIT_LIVE_KUMA_TOKEN", "")
    if not token:
        try:
            data = json.loads(PUSH_TOKENS.read_text(encoding="utf-8"))
            token = str(data.get(KUMA_PUSH_KEY, "") or "")
        except (OSError, ValueError):
            token = ""
    if not token:
        print("qflix-audit-live: WARNING no Kuma push token under '"
              + KUMA_PUSH_KEY + "' - heartbeat NOT pushed; monitor '"
              + MONITOR_NAME + "' will go red, correctly", file=sys.stderr)
        return

    try:
        port = (SECRETS_DIR / "uptimekuma.port").read_text(encoding="utf-8").strip()
    except OSError:
        port = ""
    if not port:
        print("qflix-audit-live: WARNING no uptimekuma.port - heartbeat NOT pushed",
              file=sys.stderr)
        return

    qs = urllib.parse.urlencode({"status": status, "msg": msg[:200]})
    url = "http://127.0.0.1:" + port + "/api/push/" + token + "?" + qs
    try:
        with urllib.request.urlopen(url, timeout=15) as resp:
            resp.read()
    except Exception as exc:                                  # noqa: BLE001
        print("qflix-audit-live: heartbeat push failed: " + repr(exc),
              file=sys.stderr)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="qflix-audit-live", description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--push-kuma", action="store_true",
                    help="push a heartbeat to this auditor's own Kuma monitor")
    ap.add_argument("--expected-monitors", default="",
                    help="comma-separated monitor names expected to exist")
    args = ap.parse_args(argv)

    expected = [m.strip() for m in args.expected_monitors.split(",") if m.strip()]
    result = collect(expected)
    result["recorded_at"] = _dt.datetime.now(
        _dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    result["monitor"] = MONITOR_NAME

    try:
        STATE_DIR.mkdir(parents=True, exist_ok=True)
        (STATE_DIR / "last-audit.json").write_text(
            json.dumps(result, indent=2, sort_keys=True), encoding="utf-8")
    except OSError as exc:
        # Loud, not silent: an audit whose artefact never lands is an audit that
        # did not happen, and this is exactly the class C-09 is about.
        print(f"qflix-audit-live: cannot write state: {exc}", file=sys.stderr)
        return EXIT_CANNOT_AUDIT

    if args.json:
        print(json.dumps(result, indent=2, sort_keys=True))
    else:
        print(f"qflix-audit-live: {len(result['findings'])} findings; "
              f"coverage={result['coverage']}")

    partial = any(v == "unavailable" for v in result["coverage"].values())
    if partial:
        # "I could not look" must never be reported as "I looked and it is fine".
        print("qflix-audit-live: some live classes were UNAVAILABLE — "
              "treat this run as partial", file=sys.stderr)

    if args.push_kuma:
        # DOWN on drift, and DOWN on partial coverage. Drift means the box no
        # longer matches the repo, which is the entire reason this runs; and a
        # run that could not look must never read as a clean one.
        n = len(result["findings"])
        if n:
            kinds = sorted({f.get("class", "?") for f in result["findings"]})
            _push_kuma("down",
                       "live-drift " + str(n) + " finding(s): " + ",".join(kinds))
        elif partial:
            unavail = sorted(k for k, v in result["coverage"].items()
                             if v == "unavailable")
            _push_kuma("down", "PARTIAL - could not check: " + ",".join(unavail))
        else:
            checked = sorted(k for k, v in result["coverage"].items()
                             if v == "checked")
            _push_kuma("up", "live audit clean: " + ",".join(checked))

    return EXIT_FINDINGS if result["findings"] else EXIT_OK


if __name__ == "__main__":
    raise SystemExit(main())
