"""lib/proxygen.py - render the box-2 reverse-proxy config from manifest/apps.yaml (QFLX-41).

Pure function of (apps.yaml, secrets dir, flavor, domain): no I/O beyond reading
those, deterministic output, so goldens and `diff` drift checks work. Two D-2
flavors from one routing table:

  caddy  user-space Caddy, automatic ACME TLS (email optional)
  nginx  user-space nginx server blocks; TLS certs are the operator's
         (@@CERTDIR@@ is substituted by the installer)

Routing (mirrors the Ultra panel layout):
  * qflix-dash          -> the apex `/` (the dashboard root)
  * seerr               -> its OWN vhost  seerr.<domain>  (Seerr has no base path)
  * apps with a urlbase -> `/<urlbase>/` passed through unchanged (arrs, bazarr..)
  * other apps with a port -> `/<slug>/` with the prefix stripped
  * never proxied: plex (clients hit it directly), flaresolverr and victorialogs
    (internal only). Apps without a port_secret have no route.
A missing/invalid port secret is a HARD error: a silently dropped route is an
outage nobody notices until a member does.

Loaded by file path or as `lib.proxygen`; CLI:
  proxygen.py render --flavor caddy|nginx --domain D [--email E]
                     [--manifest P] [--secrets-dir P]   exit 0 / 1 error / 2 bad input
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import List, Optional, Tuple

import yaml

FLAVORS = ("caddy", "nginx")
NEVER_PROXIED = frozenset({"plex", "flaresolverr", "victorialogs"})
DASH = "qflix-dash"
VHOST_APPS = frozenset({"seerr"})
# Apps whose urlbase is built into the app but not declared as a urlbase_secret.
STATIC_URLBASE = {"sabnzbd": "sabnzbd"}

_DOMAIN_RE = re.compile(
    r"^(?=.{1,253}$)[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?"
    r"(\.[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?)+$")
_SLUG_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$")
_EMAIL_RE = re.compile(r"^[^\s@;{}]+@[^\s@;{}]+$")


class ProxyGenError(Exception):
    pass


class BadInput(ProxyGenError):
    """Caller passed an invalid flavor/domain/email (CLI exit 2)."""


def _secret(sec: Path, name: str) -> Optional[str]:
    p = sec / name
    if not p.is_file():
        return None
    v = p.read_text(encoding="utf-8").strip()
    return v or None


def _port(sec: Path, app: str, secret_name: str) -> int:
    raw = _secret(sec, secret_name)
    if raw is None:
        raise ProxyGenError("missing secret %s (needed for %s)" % (secret_name, app))
    if not raw.isdigit() or not (1 <= int(raw) <= 65535):
        raise ProxyGenError("invalid port in %s for %s: %r" % (secret_name, app, raw))
    return int(raw)


def routes(manifest_path, secrets_dir) -> Tuple[int, List[Tuple[str, str, int]], List[Tuple[str, int]]]:
    """-> (dash_port, [(slug, urlbase_or_empty, port)] path routes, [(slug, port)] vhosts)."""
    sec = Path(secrets_dir)
    data = yaml.safe_load(Path(manifest_path).read_text(encoding="utf-8")) or {}
    dash: Optional[int] = None
    paths: List[Tuple[str, str, int]] = []
    vhosts: List[Tuple[str, int]] = []
    apps = data.get("apps") or {}
    for slug in sorted(apps):
        health = (apps[slug] or {}).get("health") or {}
        psec = health.get("port_secret")
        if not psec or slug in NEVER_PROXIED:
            continue
        if not _SLUG_RE.match(slug):
            raise ProxyGenError("unsafe slug %r" % slug)
        port = _port(sec, slug, psec)
        if slug == DASH:
            dash = port
        elif slug in VHOST_APPS:
            vhosts.append((slug, port))
        else:
            ub = ""
            if health.get("urlbase_secret"):
                ub = (_secret(sec, health["urlbase_secret"]) or "").strip("/")
            ub = ub or STATIC_URLBASE.get(slug, "")
            if ub and not _SLUG_RE.match(ub):
                raise ProxyGenError("unsafe urlbase %r for %s" % (ub, slug))
            paths.append((slug, ub, port))
    if dash is None:
        raise ProxyGenError("no %s port: the apex root has nothing to serve" % DASH)
    return dash, paths, vhosts


def _caddy(domain, email, dash, paths, vhosts) -> str:
    o = ["# Generated by scripts/maint/lib/proxygen.py from manifest/apps.yaml - do not hand-edit.",
         "{"]
    if email:
        o.append("\temail %s" % email)
    o += ["\tadmin off", "}", "", "%s {" % domain]
    for slug, ub, port in paths:
        if ub:
            o += ["\thandle /%s/* {" % ub, "\t\treverse_proxy 127.0.0.1:%d" % port, "\t}"]
        else:
            o += ["\thandle_path /%s/* {" % slug, "\t\treverse_proxy 127.0.0.1:%d" % port, "\t}"]
    o += ["\thandle {", "\t\treverse_proxy 127.0.0.1:%d" % dash, "\t}", "}", ""]
    for slug, port in vhosts:
        o += ["%s.%s {" % (slug, domain), "\treverse_proxy 127.0.0.1:%d" % port, "}", ""]
    return "\n".join(o)


_NGINX_HDRS = [
    "proxy_http_version 1.1;",
    "proxy_set_header Host $host;",
    "proxy_set_header X-Forwarded-Host $http_host;",
    "proxy_set_header X-Forwarded-Proto $scheme;",
    "proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
    "proxy_set_header Upgrade $http_upgrade;",
    'proxy_set_header Connection "upgrade";',
]


def _nginx_server(name, locations) -> List[str]:
    o = ["server {", "    listen 80;", "    server_name %s;" % name,
         "    return 301 https://$host$request_uri;", "}", "",
         "server {", "    listen 443 ssl;", "    server_name %s;" % name,
         "    ssl_certificate     @@CERTDIR@@/%s/fullchain.pem;" % name,
         "    ssl_certificate_key @@CERTDIR@@/%s/privkey.pem;" % name]
    for loc, target in locations:
        o += ["    location %s {" % loc, "        proxy_pass %s;" % target]
        o += ["        " + h for h in _NGINX_HDRS]
        o.append("    }")
    o += ["}", ""]
    return o


def _nginx(domain, _email, dash, paths, vhosts) -> str:
    o = ["# Generated by scripts/maint/lib/proxygen.py from manifest/apps.yaml - do not hand-edit.",
         "# @@CERTDIR@@ is replaced by the installer with the operator's cert directory.", ""]
    locs: List[Tuple[str, str]] = []
    for slug, ub, port in paths:
        if ub:
            locs.append(("/%s/" % ub, "http://127.0.0.1:%d" % port))
        else:   # a trailing slash on proxy_pass strips the /slug/ prefix
            locs.append(("/%s/" % slug, "http://127.0.0.1:%d/" % port))
    locs.append(("/", "http://127.0.0.1:%d" % dash))
    o += _nginx_server(domain, locs)
    for slug, port in vhosts:
        o += _nginx_server("%s.%s" % (slug, domain), [("/", "http://127.0.0.1:%d" % port)])
    return "\n".join(o)


def render(manifest_path, secrets_dir, flavor: str, domain: str, email: str = "") -> str:
    if flavor not in FLAVORS:
        raise BadInput("unknown flavor %r (want %s)" % (flavor, "|".join(FLAVORS)))
    if not _DOMAIN_RE.match(domain or ""):
        raise BadInput("invalid domain %r" % domain)
    if email and not _EMAIL_RE.match(email):
        raise BadInput("invalid email %r" % email)
    dash, paths, vhosts = routes(manifest_path, secrets_dir)
    fn = _caddy if flavor == "caddy" else _nginx
    return fn(domain, email, dash, paths, vhosts)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(prog="proxygen.py")
    sub = ap.add_subparsers(dest="cmd", required=True)
    r = sub.add_parser("render")
    r.add_argument("--flavor", required=True)
    r.add_argument("--domain", required=True)
    r.add_argument("--email", default="")
    root = Path(__file__).resolve().parents[3]
    r.add_argument("--manifest", default=str(root / "manifest" / "apps.yaml"))
    r.add_argument("--secrets-dir", default=str(root / "secrets"))
    a = ap.parse_args(argv)
    try:
        sys.stdout.write(render(a.manifest, a.secrets_dir, a.flavor, a.domain, a.email))
    except BadInput as exc:
        sys.stderr.write("proxygen: %s\n" % exc)
        return 2
    except ProxyGenError as exc:
        sys.stderr.write("proxygen: %s\n" % exc)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
