#!/usr/bin/env bash
# 35-sync-appdata.sh -- move every app's STATE blue -> green (spec 8 row 35:
# "Slim: VACUUM INTO / pg_dump; re-point PUTs only on a port collision").
#
# WHAT MOVES (every app list generated by migrate_manifest.py from the manifest):
#   E. roster + gate FIRST (I-5): green's --execute drop-in removed and
#      ~/secrets/members.yaml copied with `armed: false` forced and read back.
#   A. sqlite-tree apps (the arrs, prowlarr, bazarr x2, seerr, tautulli, sab):
#      green unit stopped, ~/.apps/<slug> copied with every sqlite file
#      snapshotted by `VACUUM INTO` on blue (consistent while blue keeps
#      running, I-2), unit started. The arr DBs carry the reaper's `permanent`
#      tags. Blue's port/key/urlbase follow the data into green's secrets
#      (the restored config listens there) UNLESS that port is taken on green:
#      then green keeps its own claimed port, the arr-family config.xml <Port>
#      is patched, and the port goes into the re-point map (F).
#   B. qbit-profile: the qBittorrent profile dirs (final pass: in the freeze).
#   C. pg-dump: `pg_dumpall --globals-only` + `pg_dump -Fc` per database from
#      blue's postgres into green's native postgres (A13 shape), green
#      listmonk stopped meanwhile, then per-table row counts compared.
#   D. state trees (migrate.conf STATE_TREES): ~/.opt/maint (reaper state,
#      entitlement state, swap state, notify.log + ledgers), Kometa config,
#      Tdarr DB2 (flows) + configs, VictoriaLogs data. Green units of the
#      state-paths apps are stopped around the copy.
#   F. re-point: repoint.py rewrites links that named blue's docker gateway
#      (Ultra only) or a collided port. Nothing else is PUT.
#   NOT moved: plex (P1: new identity on box 2, spec 7), stateless/rendered apps.
#
# DIRECTION: copies are initiated ON BLUE (rsync to NEW_HOST as blue reaches
# it), like 30. Blue writes only to a scratch dir ~/.cache/qflix-migrate (the
# VACUUM INTO targets), removed after each copy.
#
# I-3 plan only without --execute (no ssh). I-4 every step re-runnable.
# USAGE: 35-sync-appdata.sh NEW_HOST [--old-host HOST] [--execute]
# EXIT:  0 ok | 1 >=1 step failed (STAGE lines name them) | 2 refused
set -uo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/_common.sh"

usage() { echo "usage: $0 NEW_HOST [--old-host HOST] [--execute]" >&2; }
mig_args "" "$@"
need_new_host
need_tables

FAILS=0
note_fail() { printf 'STAGE=%s msg=%s\n' "$1" "${2// /-}" >&2; FAILS=$((FAILS + 1)); }

mapfile -t SQLITE_APPS < <(mm apps --strategy sqlite-tree)
mapfile -t QBIT_APPS   < <(mm apps --strategy qbit-profile)
mapfile -t PG_APPS     < <(mm apps --strategy pg-dump)
mapfile -t STATE_APPS  < <(mm apps --strategy state-paths)
[ "${#SQLITE_APPS[@]}" -gt 0 ] || stage 2 manifest-table "no-sqlite-tree-apps"

echo "=== 35-sync-appdata: blue -> $NEW_HOST ($([ "$EXECUTE" -eq 1 ] && echo EXECUTE || echo dry-run)) ==="
plan "E green: $(gate_disarm_cmd | cut -c1-60)... ; ~/$MEMBERS_REL <- blue copy with armed: false (read back)"
for row in "${SQLITE_APPS[@]}"; do
  IFS=$'\t' read -r name _c slug _w unit _s dir _p <<<"$row"
  plan "A $name: stop $unit; VACUUM INTO + rsync ~/$dir (excl $APP_TREE_EXCLUDES); port/key/urlbase follow; start"
done
for row in "${QBIT_APPS[@]}"; do
  IFS=$'\t' read -r name _c _s _w unit _rest <<<"$row"
  plan "B $name: stop $unit; rsync ${QBIT_PROFILE_DIRS[*]}; start"
done
for row in "${PG_APPS[@]}"; do
  IFS=$'\t' read -r name _rest <<<"$row"
  plan "C $name: pg_dumpall --globals-only + pg_dump -Fc (${PG_DATABASES[*]}) blue -> green native postgres; row counts compared"
done
for t in "${STATE_TREES[@]}"; do
  IFS='|' read -r rel ex dst <<<"$t"
  plan "D state: ~/$rel -> green ~/${dst:-$rel} (excl ${ex:-none})"
done
plan "D around state: stop/start $(for r in "${STATE_APPS[@]}"; do printf '%s ' "$(cut -f5 <<<"$r")"; done)"
plan "F repoint.py on green: blue docker gateway -> green net.app_host; collided ports -> green ports"
if [ "$EXECUTE" -ne 1 ]; then
  echo "[dry-run] no ssh made, nothing changed. Re-run with --execute."
  exit 0
fi

resolve_old_host
sshb true >/dev/null 2>&1 || stage 2 blue-unreachable "ssh-to-OLD_HOST-failed"
sshg true >/dev/null 2>&1 || stage 2 green-unreachable "ssh-to-NEW_HOST-failed"
window_guard
mkdir -p "$GREEN_SECRETS"

# green lifecycle: appctl when green's manifest says the app is native there,
# else the unit directly (box 2 runs everything natively, spec section 1).
glc() {  # glc VERB APP UNIT
  sshg "if ~/bin/appctl is-native $2 >/dev/null 2>&1; then ~/bin/appctl $1 $2; else systemctl --user $1 $3; fi" >/dev/null 2>&1
}

# copy_tree SRC_REL EXCLUDES TAG [DST_REL] -- runs ON blue. Sqlite files are
# never copied live: each is snapshotted with VACUUM INTO into a scratch dir
# first. DST_REL (default SRC_REL) is the destination under green's $HOME.
copy_tree() {
  local dst="${4:-$1}"
  sshb "bash -s -- $(printf '%q ' "$1" "$2" "$3" "$NEW_HOST" "$dst")" <<'BLUE'
set -uo pipefail
SRC_REL="$1"; EXCL="$2"; TAG="$3"; GREEN="$4"; DST_REL="$5"
SRC="$HOME/$SRC_REL"; SCR="$HOME/.cache/qflix-migrate/$TAG"
[ -d "$SRC" ] || { echo "missing-on-blue:$SRC_REL"; exit 3; }
rm -rf "$SCR"; mkdir -p "$SCR"
ARGS=(-a --partial --rsync-path="mkdir -p $DST_REL && rsync")
IFS=',' read -r -a PATS <<<"$EXCL"
for p in "${PATS[@]}"; do [ -n "$p" ] && ARGS+=(--exclude="$p"); done
for p in '*.db' '*.sqlite' '*.sqlite3' '*-wal' '*-shm' '*-journal'; do ARGS+=(--exclude="$p"); done
skip() { local rel="/$1" p; for p in "${PATS[@]}"; do [ -n "$p" ] || continue
  case "$rel" in */$p/*|*/$p) return 0 ;; esac; done; return 1; }
while IFS= read -r -d '' f; do
  rel="${f#$SRC/}"; skip "$rel" && continue
  mkdir -p "$SCR/$(dirname "$rel")"
  sqlite3 "$f" ".timeout 15000" "VACUUM INTO '$SCR/$rel'" || { echo "vacuum-failed:$rel"; rm -rf "$SCR"; exit 1; }
done < <(find "$SRC" -type f \( -name '*.db' -o -name '*.sqlite' -o -name '*.sqlite3' \) -print0)
rsync "${ARGS[@]}" "$SRC/" "$GREEN:$DST_REL/" || { rm -rf "$SCR"; exit 1; }
rsync -a "$SCR/" "$GREEN:$DST_REL/" || { rm -rf "$SCR"; exit 1; }
rm -rf "$SCR"
BLUE
  local rc=$?
  [ "$rc" -eq 0 ] || return "$rc"
  # The snapshots carry no WAL. A -wal/-shm left by green's own (stopped) app
  # would be replayed onto the restored file and corrupt it: remove them.
  sshg "find ~/$dst -type f \( -name '*-wal' -o -name '*-shm' -o -name '*-journal' \) -delete" >/dev/null 2>&1
}

# --- E. gate + roster (I-5: green disarmed BEFORE any data lands) -------------
sshg "$(gate_disarm_cmd)" >/dev/null 2>&1 || note_fail green-gate-disarm "drop-in-removal-failed"
if sshb "test -f ~/$MEMBERS_REL" 2>/dev/null; then
  sshb "cat ~/$MEMBERS_REL" | sshg "mkdir -p ~/secrets && python3 -c '
import sys, yaml
d = yaml.safe_load(sys.stdin) or {}
d[\"armed\"] = False
open(sys.argv[1], \"w\").write(yaml.safe_dump(d, sort_keys=False))
' ~/$MEMBERS_REL && chmod 600 ~/$MEMBERS_REL" || note_fail roster-copy "members.yaml-copy-failed"
  ARMED="$(sshg "python3 -c 'import yaml,os; print(yaml.safe_load(open(os.path.expanduser(\"~/$MEMBERS_REL\"))).get(\"armed\"))'" 2>/dev/null | tr -d '\r')"
  [ "$ARMED" = False ] || note_fail roster-armed "green-members.yaml-armed=$ARMED-(want-False)"
else
  note_fail roster-missing "no-members.yaml-on-blue"
fi

# --- A. sqlite-tree apps ------------------------------------------------------
declare -A PORT_MAP=()
for row in "${SQLITE_APPS[@]}"; do
  IFS=$'\t' read -r name _c slug _w unit _s dir psec <<<"$row"
  log_info "A $name"
  glc stop "$name" "$unit"
  bport=""; [ -n "$psec" ] && secret_exists "$psec" && bport="$(secret_read "$psec")"
  gport=""; [ -n "$psec" ] && [ -s "$GREEN_SECRETS/$psec" ] && gport="$(tr -d '[:space:]' < "$GREEN_SECRETS/$psec")"
  collided=0
  if [ -n "$bport" ] && [ "$bport" != "$gport" ] \
     && [ -n "$(sshg "ss -tlnH 'sport = :$bport'" 2>/dev/null)" ]; then
    collided=1
  fi
  if ! out="$(copy_tree "$dir" "$APP_TREE_EXCLUDES" "$slug" 2>&1)"; then
    note_fail "$name-copy" "$out"; glc start "$name" "$unit"; continue
  fi
  for ext in key urlbase; do
    secret_exists "$slug.$ext" && cp -f "$SECRETS_DIR/$slug.$ext" "$GREEN_SECRETS/$slug.$ext"
  done
  if [ "$collided" -eq 1 ]; then
    if sshg "test -f ~/$dir/config.xml"; then
      sshg "sed -i -E 's#<Port>[0-9]+</Port>#<Port>$gport</Port>#' ~/$dir/config.xml" \
        || note_fail "$name-port-patch" "config.xml-port-patch-failed"
      PORT_MAP[$bport]="$gport"
      log_warn "$name: blue port $bport is taken on green; kept green port $gport (re-pointed in F)"
    else
      note_fail "$name-port-collision" "blue-port-$bport-taken-on-green;-no-config.xml-to-patch;-operator-decides"
    fi
  elif [ -n "$bport" ]; then
    printf '%s\n' "$bport" > "$GREEN_SECRETS/$psec"
  fi
  for ext in port key urlbase; do
    [ -f "$GREEN_SECRETS/$slug.$ext" ] && scp "${MIG_SSH_OPTS[@]}" "$GREEN_SECRETS/$slug.$ext" \
      "$NEW_HOST:~/secrets/$slug.$ext" >/dev/null 2>&1
  done
  glc start "$name" "$unit" || note_fail "$name-start" "green-unit-start-failed"
done

# --- B. qBittorrent profile ----------------------------------------------------
for row in "${QBIT_APPS[@]}"; do
  IFS=$'\t' read -r name _c slug _w unit _rest <<<"$row"
  log_info "B $name"
  glc stop "$name" "$unit"
  for d in "${QBIT_PROFILE_DIRS[@]}"; do
    out="$(copy_tree "$d" "logs" "$slug-$(basename "$d")" 2>&1)" || note_fail "$name-profile" "$d:$out"
  done
  for ext in port user password; do
    secret_exists "$slug.$ext" && cp -f "$SECRETS_DIR/$slug.$ext" "$GREEN_SECRETS/$slug.$ext" \
      && scp "${MIG_SSH_OPTS[@]}" "$SECRETS_DIR/$slug.$ext" "$NEW_HOST:~/secrets/$slug.$ext" >/dev/null 2>&1
  done
  glc start "$name" "$unit" || note_fail "$name-start" "green-unit-start-failed"
done

# --- C. postgres ---------------------------------------------------------------
COUNTS_SQL="select table_name||' '||(xpath('/row/c/text()', query_to_xml(format('select count(*) as c from public.%I', table_name), false, true, '')))[1]::text from information_schema.tables where table_schema='public' and table_type='BASE TABLE' order by 1"
for row in "${PG_APPS[@]}"; do
  IFS=$'\t' read -r name _rest <<<"$row"
  log_info "C $name"
  BP="$(secret_read postgres.port 2>/dev/null)"; GP="$(tr -d '[:space:]' < "$GREEN_SECRETS/postgres.port" 2>/dev/null)"
  if [ -z "$BP" ] || [ -z "$GP" ]; then note_fail pg-ports "postgres.port-missing-(blue=$BP-green=$GP)"; continue; fi
  BENV="PGPASSWORD=\$($BLUE_PG_PASSWORD_CMD)"
  GENV='PGPASSWORD=$(cat ~/secrets/postgres.password)'
  sshg "systemctl --user stop listmonk.service" >/dev/null 2>&1
  sshb "$BENV pg_dumpall -h 127.0.0.1 -p $BP -U $PG_USER --globals-only" \
    | sshg "$GENV psql -h 127.0.0.1 -p $GP -U $PG_USER -d postgres -q -v ON_ERROR_STOP=0 >/dev/null 2>&1; exit 0" \
    || note_fail pg-globals "globals-restore-failed"
  for db in "${PG_DATABASES[@]}"; do
    sshg "$GENV createdb -h 127.0.0.1 -p $GP -U $PG_USER $db >/dev/null 2>&1; exit 0"
    sshb "$BENV pg_dump -h 127.0.0.1 -p $BP -U $PG_USER -Fc -d $db" \
      | sshg "$GENV pg_restore -h 127.0.0.1 -p $GP -U $PG_USER -d $db --clean --if-exists --no-owner" \
      || note_fail "pg-$db" "pg_dump|pg_restore-nonzero"
    bc="$(sshb "$BENV psql -h 127.0.0.1 -p $BP -U $PG_USER -d $db -tAc \"$COUNTS_SQL\"" 2>/dev/null)"
    gc="$(sshg "$GENV psql -h 127.0.0.1 -p $GP -U $PG_USER -d $db -tAc \"$COUNTS_SQL\"" 2>/dev/null)"
    if [ -z "$bc" ] || [ "$bc" != "$gc" ]; then
      note_fail "pg-$db-rowcount" "blue/green-row-counts-differ-or-unreadable;-re-run-35-in-the-freeze"
    fi
  done
  sshg "systemctl --user start listmonk.service" >/dev/null 2>&1 || note_fail listmonk-start "green"
done

# --- D. master-era state trees -------------------------------------------------
for row in "${STATE_APPS[@]}"; do IFS=$'\t' read -r name _c _s _w unit _r <<<"$row"; glc stop "$name" "$unit"; done
for t in "${STATE_TREES[@]}"; do
  IFS='|' read -r rel ex dst <<<"$t"
  log_info "D ~/$rel -> ~/${dst:-$rel}"
  out="$(copy_tree "$rel" "$ex" "state-$(printf '%s' "$rel" | tr '/.' '__')" "${dst:-$rel}" 2>&1)" \
    || note_fail state-copy "$rel:$out"
done
for row in "${STATE_APPS[@]}"; do
  IFS=$'\t' read -r name _c _s _w unit _r <<<"$row"
  [ "$(cut -f2 <<<"$row")" = cron ] && continue     # oneshots: their timer starts them
  glc start "$name" "$unit" || note_fail "$name-start" "green-unit-start-failed"
done

# --- F. re-point (only gateway change + collided ports) ------------------------
OLD_GW="$(mm docker-gateway --profile "$OLD_PROFILE" | tr -d '\r')"
NEW_APP_HOST="$(tr -d '[:space:]' < "$GREEN_SECRETS/net.app_host" 2>/dev/null)"; NEW_APP_HOST="${NEW_APP_HOST:-127.0.0.1}"
OLDH="[]"; [ -n "$OLD_GW" ] && [ "$OLD_GW" != "$NEW_APP_HOST" ] && OLDH="[\"$OLD_GW\"]"
PM="{"; sep=""; for k in "${!PORT_MAP[@]}"; do PM="$PM$sep\"$k\": \"${PORT_MAP[$k]}\""; sep=", "; done; PM="$PM}"
fam_list() { mm apps --strategy sqlite-tree | awk -F'\t' -v f="$1" '$1 ~ f {printf "%s\"%s\"", (n++?",":""), $3}'; }
PLAN="{\"old_hosts\": $OLDH, \"new_host\": \"$NEW_APP_HOST\", \"port_map\": $PM, \"arrs\": [$(fam_list '^(sonarr|radarr)')], \"prowlarr\": [$(fam_list '^prowlarr$')], \"seerr\": [$(fam_list '^seerr$')], \"bazarr\": [$(fam_list '^bazarr')]}"
log_info "F repoint plan: $PLAN"
out="$(on_box g repoint.py "$PLAN" 2>&1)" || note_fail repoint "$(printf '%s' "$out" | tail -n 3 | tr '\n' ';')"
printf '%s\n' "$out" | sed 's/^/    /'

if [ "$FAILS" -gt 0 ]; then
  printf 'FAIL: sync-appdata -- %d step(s) failed (STAGE lines above). Re-run: every step is idempotent (I-4).\n' "$FAILS"
  exit 1
fi
echo "PASS: sync-appdata -> $NEW_HOST"
exit 0
